import { IPriceModel } from "../interfaces/IPricesmodel";
import PriceModel from "../models/PriceModel";

const priceSeeder = async () => {
  try {
    const prices: IPriceModel[] = [
      {
        model: "Onn",
        inches: "24",
        unitPrice: 1500.0,
        isSpecial: false,
      },
      {
        model: "Onn",
        inches: "32",
        unitPrice: 1900.0,
        isSpecial: false,
      },
      {
        model: "Onn",
        inches: "40",
        unitPrice: 2750.0,
        isSpecial: false,
      },
      {
        model: "Onn",
        inches: "43",
        unitPrice: 3200.0,
        isSpecial: false,
      },
      {
        model: "Onn",
        inches: "50",
        unitPrice: 4000.0,
        isSpecial: false,
      },
      {
        model: "Onn",
        inches: "55",
        unitPrice: 5000.0,
        isSpecial: false,
      },
      {
        model: "Onn",
        inches: "65",
        unitPrice: 7000.0,
        isSpecial: false,
      },
      {
        model: "Onn",
        inches: "75",
        unitPrice: 12000.0,
        isSpecial: false,
      },
      {
        model: "TCL",
        inches: "32",
        unitPrice: 1900.0,
        isSpecial: false,
      },
      {
        model: "TCL",
        inches: "40",
        unitPrice: 2750.0,
        isSpecial: false,
      },
      {
        model: "TCL",
        inches: "43",
        unitPrice: 3200.0,
        isSpecial: false,
      },
      {
        model: "TCL",
        inches: "50",
        unitPrice: 4000.0,
        isSpecial: false,
      },
      {
        model: "TCL",
        inches: "55",
        unitPrice: 5000.0,
        isSpecial: false,
      },
      {
        model: "TCL",
        inches: "58",
        unitPrice: 5500.0,
        isSpecial: false,
      },
      {
        model: "TCL",
        inches: "65",
        unitPrice: 7000.0,
        isSpecial: false,
      },
      {
        model: "TCL",
        inches: "70",
        unitPrice: 9000.0,
        isSpecial: false,
      },
      {
        model: "TCL",
        inches: "75",
        unitPrice: 12000.0,
        isSpecial: false,
      },
      {
        model: "Samsung",
        inches: "32",
        unitPrice: 2200.0,
        isSpecial: false,
      },
      {
        model: "Samsung",
        inches: "40",
        unitPrice: 2900.0,
        isSpecial: false,
      },
      {
        model: "Samsung",
        inches: "43",
        unitPrice: 3500.0,
        isSpecial: false,
      },
      {
        model: "Samsung",
        inches: "50",
        unitPrice: 4500.0,
        isSpecial: false,
      },
      {
        model: "Samsung",
        inches: "55",
        unitPrice: 5500.0,
        isSpecial: false,
      },
      {
        model: "Samsung",
        inches: "60",
        unitPrice: 6500.0,
        isSpecial: false,
      },
      {
        model: "Samsung",
        inches: "65",
        unitPrice: 7500.0,
        isSpecial: false,
      },
      {
        model: "Samsung",
        inches: "70",
        unitPrice: 11000.0,
        isSpecial: false,
      },
      {
        model: "Samsung",
        inches: "75",
        unitPrice: 12000.0,
        isSpecial: false,
      },
      {
        model: "Samsung",
        inches: "85",
        unitPrice: 16000.0,
        isSpecial: false,
      },
      {
        model: "LG",
        inches: "32",
        unitPrice: 2000.0,
        isSpecial: false,
      },
      {
        model: "LG",
        inches: "43",
        unitPrice: 3200.0,
        isSpecial: false,
      },
      {
        model: "LG",
        inches: "50",
        unitPrice: 4500.0,
        isSpecial: false,
      },
      {
        model: "LG",
        inches: "55",
        unitPrice: 5500.0,
        isSpecial: false,
      },
      {
        model: "LG",
        inches: "65",
        unitPrice: 7000.0,
        isSpecial: false,
      },
      {
        model: "LG",
        inches: "70",
        unitPrice: 10000.0,
        isSpecial: false,
      },
      {
        model: "LG",
        inches: "75",
        unitPrice: 12000.0,
        isSpecial: false,
      },
      {
        model: "Westinghouse",
        inches: "32",
        unitPrice: 2000.0,
        isSpecial: false,
      },
      {
        model: "Westinghouse",
        inches: "43",
        unitPrice: 3200.0,
        isSpecial: false,
      },
      {
        model: "Westinghouse",
        inches: "50",
        unitPrice: 4000.0,
        isSpecial: false,
      },
      {
        model: "Westinghouse",
        inches: "55",
        unitPrice: 5000.0,
        isSpecial: false,
      },
      {
        model: "Westinghouse",
        inches: "58",
        unitPrice: 6000.0,
        isSpecial: false,
      },
      {
        model: "Westinghouse",
        inches: "65",
        unitPrice: 7000.0,
        isSpecial: false,
      },
      {
        model: "Hisense",
        inches: "40",
        unitPrice: 2750.0,
        isSpecial: false,
      },
      {
        model: "Hisense",
        inches: "50",
        unitPrice: 4000.0,
        isSpecial: false,
      },
      {
        model: "Hisense",
        inches: "55",
        unitPrice: 5000.0,
        isSpecial: false,
      },
      {
        model: "Hisense",
        inches: "58",
        unitPrice: 6000.0,
        isSpecial: false,
      },
      {
        model: "Hisense",
        inches: "65",
        unitPrice: 7000.0,
        isSpecial: false,
      },
      {
        model: "Hisense",
        inches: "70",
        unitPrice: 10000.0,
        isSpecial: false,
      },
      {
        model: "Hisense",
        inches: "75",
        unitPrice: 12000.0,
        isSpecial: false,
      },
      {
        model: "VIZIO",
        inches: "50",
        unitPrice: 4000.0,
        isSpecial: false,
      },
      {
        model: "RCA",
        inches: "32",
        unitPrice: 1900.0,
        isSpecial: false,
      },
      {
        model: "Onn",
        inches: "24",
        unitPrice: 1750.0,
        isSpecial: true,
      },
      {
        model: "Onn",
        inches: "32",
        unitPrice: 2150.0,
        isSpecial: true,
      },
      {
        model: "Onn",
        inches: "40",
        unitPrice: 3000.0,
        isSpecial: true,
      },
      {
        model: "Onn",
        inches: "43",
        unitPrice: 3450.0,
        isSpecial: true,
      },
      {
        model: "Onn",
        inches: "50",
        unitPrice: 4250.0,
        isSpecial: true,
      },
      {
        model: "Onn",
        inches: "55",
        unitPrice: 5250.0,
        isSpecial: true,
      },
      {
        model: "Onn",
        inches: "65",
        unitPrice: 7250.0,
        isSpecial: true,
      },
      {
        model: "Onn",
        inches: "75",
        unitPrice: 12250.0,
        isSpecial: true,
      },
      {
        model: "TCL",
        inches: "32",
        unitPrice: 2150.0,
        isSpecial: true,
      },
      {
        model: "TCL",
        inches: "40",
        unitPrice: 3000.0,
        isSpecial: true,
      },
      {
        model: "TCL",
        inches: "43",
        unitPrice: 3450.0,
        isSpecial: true,
      },
      {
        model: "TCL",
        inches: "50",
        unitPrice: 4250.0,
        isSpecial: true,
      },
      {
        model: "TCL",
        inches: "55",
        unitPrice: 5250.0,
        isSpecial: true,
      },
      {
        model: "TCL",
        inches: "58",
        unitPrice: 5750.0,
        isSpecial: true,
      },
      {
        model: "TCL",
        inches: "65",
        unitPrice: 7250.0,
        isSpecial: true,
      },
      {
        model: "TCL",
        inches: "70",
        unitPrice: 9250.0,
        isSpecial: true,
      },
      {
        model: "TCL",
        inches: "75",
        unitPrice: 12250.0,
        isSpecial: true,
      },
      {
        model: "Samsung",
        inches: "32",
        unitPrice: 2450.0,
        isSpecial: true,
      },
      {
        model: "Samsung",
        inches: "40",
        unitPrice: 3150.0,
        isSpecial: true,
      },
      {
        model: "Samsung",
        inches: "43",
        unitPrice: 3750.0,
        isSpecial: true,
      },
      {
        model: "Samsung",
        inches: "50",
        unitPrice: 4750.0,
        isSpecial: true,
      },
      {
        model: "Samsung",
        inches: "55",
        unitPrice: 5750.0,
        isSpecial: true,
      },
      {
        model: "Samsung",
        inches: "60",
        unitPrice: 6750.0,
        isSpecial: true,
      },
      {
        model: "Samsung",
        inches: "65",
        unitPrice: 7750.0,
        isSpecial: true,
      },
      {
        model: "Samsung",
        inches: "70",
        unitPrice: 11250.0,
        isSpecial: true,
      },
      {
        model: "Samsung",
        inches: "75",
        unitPrice: 12250.0,
        isSpecial: true,
      },
      {
        model: "Samsung",
        inches: "85",
        unitPrice: 16250.0,
        isSpecial: true,
      },
      {
        model: "LG",
        inches: "32",
        unitPrice: 2250.0,
        isSpecial: true,
      },
      {
        model: "LG",
        inches: "43",
        unitPrice: 3450.0,
        isSpecial: true,
      },
      {
        model: "LG",
        inches: "50",
        unitPrice: 4750.0,
        isSpecial: true,
      },
      {
        model: "LG",
        inches: "55",
        unitPrice: 5750.0,
        isSpecial: true,
      },
      {
        model: "LG",
        inches: "65",
        unitPrice: 7250.0,
        isSpecial: true,
      },
      {
        model: "LG",
        inches: "70",
        unitPrice: 10250.0,
        isSpecial: true,
      },
      {
        model: "LG",
        inches: "75",
        unitPrice: 12250.0,
        isSpecial: true,
      },
      {
        model: "Westinghouse",
        inches: "32",
        unitPrice: 2150.0,
        isSpecial: true,
      },
      {
        model: "Westinghouse",
        inches: "43",
        unitPrice: 3450.0,
        isSpecial: true,
      },
      {
        model: "Westinghouse",
        inches: "50",
        unitPrice: 4250.0,
        isSpecial: true,
      },
      {
        model: "Westinghouse",
        inches: "55",
        unitPrice: 5250.0,
        isSpecial: true,
      },
      {
        model: "Westinghouse",
        inches: "58",
        unitPrice: 6250.0,
        isSpecial: true,
      },
      {
        model: "Westinghouse",
        inches: "65",
        unitPrice: 7250.0,
        isSpecial: true,
      },
      {
        model: "Hisense",
        inches: "40",
        unitPrice: 3000.0,
        isSpecial: true,
      },
      {
        model: "Hisense",
        inches: "43",
        unitPrice: 3450.0,
        isSpecial: true,
      },
      {
        model: "Hisense",
        inches: "50",
        unitPrice: 4250.0,
        isSpecial: true,
      },
      {
        model: "Hisense",
        inches: "55",
        unitPrice: 5250.0,
        isSpecial: true,
      },
      {
        model: "Hisense",
        inches: "58",
        unitPrice: 6250.0,
        isSpecial: true,
      },
      {
        model: "Hisense",
        inches: "65",
        unitPrice: 7250.0,
        isSpecial: true,
      },
      {
        model: "Hisense",
        inches: "70",
        unitPrice: 10250.0,
        isSpecial: true,
      },
      {
        model: "Hisense",
        inches: "75",
        unitPrice: 12250.0,
        isSpecial: true,
      },
      {
        model: "VIZIO",
        inches: "50",
        unitPrice: 4250.0,
        isSpecial: true,
      },
    ];
    const count = await PriceModel.countDocuments();
    if (count === 0) {
      for (const pricesData of prices) {
        await PriceModel.create(pricesData);
      }
    }
  } catch (error) {
    throw new Error(`Error: ${error}`);
  }
};

export default priceSeeder;
